### ISSUE TITLE
Exception 추가 및 오류 수정

### ISSUE THREAD

**Issue by GahBaek** [mju-likelion/12th-crossover-server-3#34]
## Description
Post 및 Term 관련 Exception 추가 및
Post, Term 관련 오류 수정

### errorCode
- [ ] ErrorCode
### Controller
- [ ] ExceptionController
### Service
- [ ] TermService
- [ ] PostService
- [ ] CommentService

**Comment by jihyeonEom** [comment]
약관 동의에 false를 넣어도 회원가입이 되던데 그거 수정하는 건가영??

**Comment by GahBaek** [comment]
넵 다른 api 에서도 예외랑 오류 수정 하고 있습니당,,!
